# Generated by Django 4.1 on 2022-09-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_feed_like_count_remove_feed_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='like_count',
            field=models.IntegerField(default=2),
        ),
    ]
